Bodaclick\BDKEnquiryBundle\Document\Answer:
  type: document
  collection: answers
  fields:
    id:
      id: true

  embedMany:
    responses:
      targetDocument: Response

  referenceOne:
    enquiry:
      targetDocument: Enquiry
      inversedBy: answers
      simple: true

  referenceOne:
    user: ~
