BDK\EnquiryBundle\Document\Enquiry:
  type: document
  repositoryClass: BDK\EnquiryBundle\Doctrine\ODM\MongoDB\Repository\EnquiryRepository
  collection: enquiries
  requireIndexes: true
  fields:
    id:
      id: true
    type:
      type: string
    about:
      type: string
    createdAt:
      type: date
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: date
      column: updated_at
      gedmo:
        timestampable:
          on: update
    user:
      type: string

  embedMany:
    responses:
      targetDocument: Response

  indexes:
    name:
      keys:
        type: asc
      options:
        safe: true
        sparse: true
