BDK\EnquiryBundle\Document\Enquiry:
  type: document
  repositoryClass: BDK\EnquiryBundle\Doctrine\ODM\MongoDB\Repository\EnquiryRepository
  collection: enquiries
  requireIndexes: true
  fields:
    id:
      id: true
    title:
      type: string
    type:
      type: string
    about:
      type: string
    status:
      type: string
    createdAt:
      type: date
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: date
      column: updated_at
    expiresAt:
      type: date
      column: expires_at
    sent:
      type: boolean
      column: sent
    user:
      type: string

  embedMany:
    responses:
      targetDocument: Response

  indexes:
    type:
      keys:
        type: asc
      options:
        safe: true
        sparse: true
    user:
      keys:
        user: asc
      options:
        safe: true
    about:
      keys:
        about: asc
      options:
        safe: true
        sparse: true
    sent:
      keys:
        sent: asc
      options:
        safe: true

