BDK\EnquiryBundle\Entity\Enquiry:
  type: entity
  repositoryClass: BDK\EnquiryBundle\Doctrine\ORM\Repository\EnquiryRepository
  table: enquiry
  indexes:
    type_index:
      columns: [type]
    about_index:
      columns: [about]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    type:
      type: string
      length: 255
      nullable: false
    status:
      type: string
      length: 64
      nullable: false
    createdAt:
      type: datetime
      nullable: false
      column: created_at
    updatedAt:
      type: datetime
      nullable: true
      column: updated_at
    about:
      type: string
      length: 255
    user:
      type: string
      length: 255

  oneToMany:
    responses:
      targetEntity: Response
      mappedBy: enquiry
      cascade: ["persist", "remove"]

  lifecycleCallbacks: {  }
