BDK\EnquiryBundle\Document\Enquiry:
  type: document
  repositoryClass: BDK\EnquiryBundle\Doctrine\ODM\MongoDB\Repository\EnquiryRepository
  collection: enquiries
  requireIndexes: true
  fields:
    id:
      id: true
    type:
      type: string
    created_at:
      type: datetime
    updated_at:
      type: datetime

  embedMany:
    responses:
      targetDocument: Response

  indexes:
    name:
      keys:
        type: asc
      options:
        unique: true
        safe: true
        sparse: true
#
#  referenceOne:
#    about: ~
#
#  referenceMany:
#    answers:
#      targetDocument: Answer
#      mappedBy: enquiry
