BDK\EnquiryBundle\Entity\Response:
  type: entity
  table: response
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    question:
      type: string
      length: 255
      column: question
    answer:
      type: string
      column: answer
      length: 255

  manyToOne:
    enquiry:
      targetEntity: Enquiry
      inversedBy: responses
      joinColumn:
        name: enquiry_id
        referencedColumnName: id


  lifecycleCallbacks: {  }
