parameters:
    bdk.response_mapping:
      default: BDK\EnquiryBundle\Entity\Response

services:
    bdk.response_mapping.listener:
        class: BDK\EnquiryBundle\Doctrine\ORM\EventListener\ResponseMappingListener
        public: false

    bdk.db_prefix.listener:
        class: BDK\EnquiryBundle\Doctrine\ORM\EventListener\TableNamePrefixListener
        public: false

    bdk.enquiry.object_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManager
