parameters:
    bdk.response_mapping:
      default: Bodaclick\BDKEnquiryBundle\Entity\Response

services:
    bdk.user_asocciation.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\UserAssociationListener
        arguments: [ %bdk.user_class%]
        public: false
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata}

    bdk.response_mapping.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\ResponseMappingListener
        public: false

    bdk.db_prefix.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\TableNamePrefixListener
        public: false

    bdk.link_about.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\LinkAboutListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist}
            - { name: doctrine.event_listener, event: preUpdate}
            - { name: doctrine.event_listener, event: postLoad}
            - { name: doctrine.event_listener, event: postPersist}


    bdk.enquiry.object_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManager
