parameters:
   bdk.enquiry.api.supported_formats: json|xml

services:

    bdk.enquiry.manager:
        class: BDK\EnquiryBundle\Model\Manager\EnquiryManager
        arguments:
            - @bdk.enquiry.object_manager
            - @event_dispatcher
            - BDKEnquiryBundle:Enquiry

    bdk.enquiry.service:
        alias: bdk.enquiry.manager

    bdk.enquiry.form.type.response:
        class: BDK\EnquiryBundle\Form\Type\ResponseFormType
        arguments:
            - %bdk.enquiry.default_response_class%
        tags:
            - { name: form.type, alias: response }
